services: 
    dind: 
      image: docker:dind
      privileged: true 
      volumes:
        - ./jenkins-home:/var/jenkins_home
        - ./jenkins-certs:/certs/client
      environment: 
        - DOCKER_TLS_CERTDIR=/certs
      networks:
        - jenkins 
    jenkins:
      image: viki123v/cicd-homework4-jenkins:v1
      restart: on-failure
      environment:
        - DOCKER_TLS_VERIFY=1
        - DOCKER_HOST=tcp://dind:2376
        - DOCKER_CERT_PATH=/certs/client
      ports: 
        - '50000:50000'
        - '8080:8080'
      volumes: 
        - ./jenkins-home:/var/jenkins_home
        - ./jenkins-certs:/certs/client
      networks:
        - jenkins 
networks: 
  jenkins: 
    driver: bridge


